### PR TITLE
Jibit driver added.

### PR DESCRIPTION
**Pull request by MOstadi**
in response to issue [183](https://github.com/shetabit/payment/issues/183) in payment repo

### CODE REVIEW

**Comment by khanzadimahdi** [comment]
fix your code style please.

**Comment by MOstadi** [comment]
it's ok now

**Comment by khanzadimahdi** [comment]
thanks for your great contribution. I will merge it and release it in the next version.

**Comment by MOstadi** [comment]
Jibit driver added.

**Comment by MOstadi** [comment]
it is required to set these two detail parameters to invoice before payment:
'order_id' : a unique number,
'mobile' : a unique user identifier with values like mobile

**Comment by khanzadimahdi** [comment]
Hi, thanks for your great contribution.
order_id must be auto-generate, please implement it.
and add mobile into configs.

**Comment by khanzadimahdi** [comment]
I close this PR because of a long time no activity.

**Pull request closed without merging**
