### PR TITLE
Add Vandar driver

### PR DESCRIPTION
**Pull request by amirrezakhmd**
Tested and working properly.

### CODE REVIEW

**Comment by khanzadimahdi** [comment]
cool. thanks.

**Comment by khanzadimahdi** [comment]
please fix `heavy_checgik_mark` in the docs and send another pull request.

**Comment by khanzadimahdi** [comment]
new version released =D

**Comment by amirrezakhmd** [comment]
Sorry :))
Fixed

https://github.com/shetabit/multipay/pull/145

**Pull request merged**
