### PR TITLE
Improvement AsanPardakht rest api 

### PR DESCRIPTION
**Pull request by iamammiin**
Add AsanPardakht gateway rest API methods.

Test All sections and all methods.  

fix this issue [74](https://github.com/shetabit/multipay/issues/74)

### CODE REVIEW

**Comment by khanzadimahdi** [comment]
doest it works properly? did you test it?

**Comment by iamammiin** [comment]
> doest it works properly? did you test it?

yes, test all sections and work on [LionComputer.com](https://lioncomputer.com/)

**Comment by khanzadimahdi** [comment]
thanks for your great contribution.

**Comment by khanzadimahdi** [comment]
this PR will be released in the next version.

**Comment by iamammiin** [comment]
> this PR will be released in the next version.

image
I have opened my PR sooner than the accepted PR, thus my changes are not in the last release !!!!!!

**Comment by khanzadimahdi** [comment]
send another one

**Comment by khanzadimahdi** [comment]
I am writing some unit tests in my free time.
unit tests would prevent this kind of problem.

**Pull request merged**
