### PR TITLE
added verification_token option in config

### PR DESCRIPTION
**Pull request by erfantkerfan**
## Description

added verification_token option in config.

## Motivation and context

Why is this change required? What problem does it solve?

If it fixes an issue where you have multi-gateway website and payment system and you want to verify their payment in one clean and simple code.

## How has this been tested?

this approach has been tested in https://alaatv.com
and works very nice with 'zrinpal', 'mellat', 'parsian' gateways 
but it needs to be more completed as I cant investigate all the possible gateways :)

Screenshot from 2021-06-03 16-48-21

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [ x ] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [ x ] My pull request addresses exactly one patch/feature.
- [ x ] I have created a branch for this patch/feature.
- [ x ] Each individual commit in the pull request is meaningful.
- [ ] I have added tests to cover my changes.
- [ ] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Comment by aminmohammadmazreali** [comment]
Pasargad is: iN
Saman is: ResNum
Sepehr is: invoiceid

replace this verification variable :)

**Comment by erfantkerfan** [comment]
DONE :-)

**Comment by erfantkerfan** [comment]
hence the incompatibility with laravel/octane this part must be changed but there are no incompatibility issues will arise from this chnage so it might be taged as a minor update



compatibility with laravel octane

Describe your changes in detail.

I used a more laravel friendly approach to set the request property.

Why is this change required? What problem does it solve?

It fixes total incompatibility with laravel octane.

## How has this been tested?

as this method is a solid peace of laravel framework no specific test is neede and it can be called bug proof.

## Screenshots (if appropriate)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [ x  I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [ x ] My pull request addresses exactly one patch/feature.
- [ x ] I have created a branch for this patch/feature.
- [ x ] Each individual commit in the pull request is meaningful.
- [ x ] I have added tests to cover my changes.
- [ x ] If my change requires a change to the documentation, I have updated it accordingly.

If you're unsure about any of these, don't hesitate to ask. We're here to help!

**Comment by erfantkerfan** [comment]
also I found no usage of this part in the code

```
$this->postData = $_POST;
$this->getData = $_GET;
```
so it might be good idea to remove this part and not to use it anymore

my best regards for Iranian open-source developers ❤️

**Comment by erfantkerfan** [comment]
anybody want to review this?
@iamammiin @na3r @TabrizAdmin @hsharghi

**Comment by erfantkerfan** [comment]
@khanzadimahdi

**Review by hsharghi — CHANGES_REQUESTED** [review]
This commit has an issue.
`request()` method is not available in plain `PHP`, it's only available in `Laravel`

**Comment by erfantkerfan** [comment]
@hsharghi
okay I reverted that commit but how you suggest to make this package compatible with laravel octane?

**Comment by hsharghi** [comment]
> @hsharghi
> okay I reverted that commit but how you suggest to make this package compatible with laravel octane?

The problem with Octane is that it can use with any of these two: RoadRunner and Swoole. 
Swoole has an equivalent class `Swoole\Http\Request` which can be used easily instead of global `$_REQUEST` array, but I'm not sure about RoadRunner.

**Comment by erfantkerfan** [comment]
I'm using swoole extension so that would resolve my problem but not a complete fix by every one
also the request()->all() works okay ... but as you said only with laravel
@hsharghi

**Comment by erfantkerfan** [comment]
want to merge his one for now?

**Comment by erfantkerfan** [comment]
I also fixed the problem you mentioned earlier about laravel incompatibility with my fix for octane I also have a new pull request that I will work on it a little more and perform some test but first I need this parted fixed(you can see those changes in my octane branch).

**Comment by khanzadimahdi** [comment]
I don't know why we need this feature, let review the code, then we could talk more about it

**Comment by erfantkerfan** [comment]
this is needed when you use multiple gateways in one code base and you want to get these keys and do something with them.
in this case you have to implement in the code(thats not clean at all!) or use some sort of a mapping like this to be able to get that and do something with that property in your logic
Im waiting for this merge request to be accepted (or rejected) then I would make another pool request about compatibility with octane

**Comment by hsharghi** [comment]
@erfantkerfan Sorry but I agree with @khanzadimahdi  
The verification token is only one of (but the most important) values about the payment. 
Digital receipt, payment card number and order id are some of the parameters that IPG will return on successful payment. 
They're available for some IPGs in the returned `invoice` object and more can be implemented for each driver, since it's a driver specific parameter. 
So I think it's not a feature that is required for now.

**Comment by erfantkerfan** [comment]
So I close this one

**Pull request closed without merging**
