### PR TITLE
Dev local driver

### PR DESCRIPTION
**Pull request by hsharghi**
Added `Local` driver for development purpose.
This pull request will fix https://github.com/shetabit/multipay/issues/66

## Description

`Local` driver can be initiated and verified like any other real IPGs.

## Motivation and context

Testing purchase flow in websites using real IPGs can be a pain in a** as many banks don't provide sandbox environment for development. 

## How has this been tested?

simple php script can be used to test functionality of this driver

```php

<?php

require_once 'vendor/autoload.php';

use Shetabit\Multipay\Invoice;
use Shetabit\Multipay\Payment;


$paymentConfig = require(dirname(__FILE__) . '/vendor/shetabit/multipay/config/payment.php');

$payment = new Payment($paymentConfig);

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    callback($payment);
    return;
}

initPayment($payment);

function initPayment($payment)
{
    $invoice = new Invoice();
    $invoice->amount(10000);
    $invoice->detail([
        // 'failedPurchase' => 'عدم تطابق تنظیمات با مشخصات درگاه',
        'orderId' => 4444,
    ]);

    try {
        echo $payment->via('local')
            ->callbackUrl($invoice->getDetail('callbackUrl'))
            ->purchase($invoice)
            ->pay()
            ->render();
    } catch (Exception $e) {
        echo $e->getMessage();
        die();
    }
}

function callback(Payment $payment)
{
    $transactionID = $_GET['transactionId'];

    try {
        $receipt = $payment->via('local')->verify();
    } catch (Exception $e) {
        echo $e->getMessage();
        die();
    }

    var_dump($receipt);
}
```
## Screenshots (if appropriate)

screenshot

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [ ] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

### CODE REVIEW

**Comment by khanzadimahdi** [comment]
Cool =D

**Comment by khanzadimahdi** [comment]
Does it work in Laravel too? what would happen if we use `local` driver in Laravel ?

**Comment by hsharghi** [comment]
> Does it work in Laravel too? what would happen if we use `local` driver in Laravel ?

I'm working on it. 
Currently I stuck at rendering `shetabitPayment::localForm` instead of `shetabitPayment::redirectForm`

 I think I need to talk to you about it a little bit.

**Comment by khanzadimahdi** [comment]
Ok, I will phone you tonight. 

thanks for your all contributions.

**Comment by hsharghi** [comment]
@khanzadimahdi did you check the updated readme (en/fa) files? any thoughts?

**Comment by khanzadimahdi** [comment]
thanks for your contribution.
I will release this in the next version.

**Pull request merged**
