### PR TITLE
Fix Zarinpal

### PR DESCRIPTION
**Pull request by rayansys**

### CODE REVIEW

**Comment by khanzadimahdi** [comment]
hi, have you test the changes? it works?

**Comment by rayansys** [comment]
Hi, some new changes have happened in ZarrinPal. I am making changes.
Also changes as a result of verify transaction , such as Card Number , Card Hash , ....

**Comment by aminmohammadmazreali** [comment]
> Hi, some new changes have happened in ZarrinPal. I am making changes.
> Also changes as a result of verify transaction , such as Card Number , Card Hash , ....

the URLs you were added in your last commit produce 403 forbidden nginx error in zarinpal

**Comment by rayansys** [comment]
in new version zaringate & sandbox removed

**Comment by rayansys** [comment]
> 
> 
> > Hi, some new changes have happened in ZarrinPal. I am making changes.
> > Also changes as a result of verify transaction , such as Card Number , Card Hash , ....
> 
> the URLs you were added in your last commit produce 403 forbidden nginx error in zarinpal

use post method.

**Comment by rayansys** [comment]
according to : https://docs.zarinpal.com/paymentGateway/guide/

https://api.zarinpal.com/pg/v4/payment/request.json
https://api.zarinpal.com/pg/v4/payment/verify.json

but , sandbox not work

**Comment by rayansys** [comment]
ok

**Pull request closed without merging**
