### PR TITLE
handle send cellphone number in Saman, Behpardakht, AsanPardakht, Sepehr

### PR DESCRIPTION
**Pull request by aminmohammadmazreali**
## Description

fix send cellphone number for show users card number in gateway page in

- Saman
- Behpardakht
- AsanPardakht
- Sepehr

fixed this  #39

### CODE REVIEW

**Comment by aminmohammadmazreali** [comment]
whats problem for Scrutinizer test?
@khanzadimahdi

**Comment by khanzadimahdi** [comment]
> What's the problem with the Scrutinizer test?
> @khanzadimahdi

i think its test configs must be double checked.

**Comment by khanzadimahdi** [comment]
have you test all of this changes? they work without any problems?

**Comment by aminmohammadmazreali** [comment]
> have you test all of this changes? they work without any problems?

yes tested and worked, all changes are optional, and all sections handle by gateways documentations.

**Comment by khanzadimahdi** [comment]
cool =) thanks for your contributions.

**Comment by ahbanavi** [comment]
> > What's the problem with the Scrutinizer test?
> > @khanzadimahdi
> 
> i think its test configs must be double checked.

Hi, @khanzadimahdi  you should use php: 7.4 in scrutinizer config as below:
image  

as I test it [here](https://scrutinizer-ci.com/g/ahbanavi/multipay/inspections/ee5e354f-b398-49f9-9e14-91c94a5033cb) with [my fork branch](https://github.com/ahbanavi/multipay) and everything works fine.
image.

**Comment by khanzadimahdi** [comment]
@ahbanavi  could you fix it and send a pull request?

**Pull request merged**
